Tests & Travis & sentry/sdk ^3.0
rootpd/nette-sentry pull request #4
Opened 2020-10-10 09:44 UTC by martenb

2020-10-10 16:00 UTC, martenb commented
@rootpd Can you look at it, i have changed the initialization of sentry, which should be compatible with both ^2.1 and ^3.0.
Also i have added simple tests and travis config.
Tests are not working with --prefer-lowest dependecies because of se nette BC, maybe you can fix in the future?

2020-10-13 16:37 UTC, martenb commented
@rootpd ping

2020-10-13 17:46 UTC, rootpd commented
I'm glad you had the chance and time to make the PR, and I'll get to that
eventually (review and test the changes).. But please remember, this is an
open source library, maintained in my spare time. There's no way I can just
drop the rest of my responsibilities and start working on this. And I
cannot just merge it without reviewing.




ut 13. 10. 2020 o 18:38 Martin Brettschneider <notifications@github.com>
napísal(a):

> @rootpd <https://github.com/rootpd> ping
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rootpd/nette-sentry/pull/4#issuecomment-707866089>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGGO3IFTJHC4BAUF3GS3MLSKR663ANCNFSM4SK6OIBA>
> .
>

2020-10-13 18:16 UTC, martenb commented
Ok, i have bad experiences with unmainatained libraries, so i was afraid, that this is same case, when you didnt respond.
I will use my fork now, until you have time.

2020-10-19 10:43 UTC, rootpd commented
I did not forget about you, don't worry :). Just other things piled up.

2020-10-21 08:14 UTC, rootpd requested changes
Regarding the `--prefer-lowest` issues you mentioned. I've found out that the `Tracy\Logger` constructor changed since version `2.6`, and is causing the tests you've mentioned failing for any older version. It's almost 2-year old change, so I'm keen to just dump the old versions and require `tracy/tracy: ^2.6`. It still is a non-breaking change, so it should be fine.

If that sounds OK to you, please change it in this PR.

I've tested the newer version of Tracy and for PHP 7.4 I'm still seeing some `--prefer-lowest` issues in tests which would be fixed by updating `nette/di` to `3.0` and `nette/utils` to `3.0.1`, but that would be a breaking change so we'll keep it as it is.

Once these changes are done, I think we can squash and merge this.

2020-10-21 08:14 UTC, rootpd commented on composer.json
> +    "sentry/sdk": "^2.1 || ^3.0",
I know the library itself doesn't use anything internal from the Sentry SDK so it _shouldn't_ break, but is there any reason to keep `2.*` available? It feels like we're keeping a window for some kind of failure here. I'd probably go with `^3.0` directly.

What do you think?

2020-10-21 16:17 UTC, martenb commented on composer.json
> +    "sentry/sdk": "^2.1 || ^3.0",
3.0 requires php 7.2, i think, we can support 7.1 for now...

2020-10-21 16:23 UTC, martenb commented on composer.json
> +    "sentry/sdk": "^2.1 || ^3.0",
or release version as it is and another with tracy ^2.6 and enabled prefer lowest tests

2020-10-21 16:26 UTC, martenb commented on composer.json
> +    "sentry/sdk": "^2.1 || ^3.0",
i will try it again, to fix it in tests, but i have no luck with fixing it before..

2020-10-21 18:16 UTC, martenb commented on composer.json
> +    "sentry/sdk": "^2.1 || ^3.0",
What do you think about this commit?

https://github.com/martenb/nette-sentry/commit/65952786760541e2cb39378cbedfafd19254fcf8

2020-10-22 06:12 UTC, rootpd commented on composer.json
> +    "sentry/sdk": "^2.1 || ^3.0",
The default for logging directory in (https://github.com/martenb/nette-sentry/commit/65952786760541e2cb39378cbedfafd19254fcf8) seems OK to me, we could go with that.

Regarding the `sentry/sdk`, I'd still go with `3.0`, even if the bump to PHP 7.2 is required. PHP 7.1 has not been security-supported for over a year now (https://www.php.net/supported-versions.php) so it's actually a good idea to force people to upgrade. Even 7.2 will be done in a month so this is the least we could do here.

2020-10-22 06:40 UTC, martenb commented on composer.json
> +    "sentry/sdk": "^2.1 || ^3.0",
ok, that makes sense. when we are changing libraries... why is there ext-iconv? it looks like, it is not used in library..?

2020-10-22 06:42 UTC, rootpd commented on composer.json
> +    "sentry/sdk": "^2.1 || ^3.0",
Huh, I don't really remember. Let's remove it. I'll test the master in production before I tag the new version so we'll see whether it was necessary for something or not.

2020-10-22 07:10 UTC, martenb commented on composer.json
> +    "sentry/sdk": "^2.1 || ^3.0",
uf, there was some depracations in nette, so it must look like this...

https://github.com/martenb/nette-sentry/commit/d7fce06489586f0f70272307d079fddcce2a1485

2020-10-22 07:18 UTC, rootpd commented on composer.json
> +    "sentry/sdk": "^2.1 || ^3.0",
That's OK :+1:

2020-10-22 07:19 UTC, martenb commented on composer.json
> +    "sentry/sdk": "^2.1 || ^3.0",
ok, i will rebase master

2020-10-22 07:51 UTC, rootpd commented
Thanks a lot. One last thing to discuss. On PHP 7.4 and `--prefer-lowest` composer switch I'm getting this deprecation error:

```
> tester -C tests
 _____ ___  ___ _____ ___  ___
|_   _/ __)( __/_   _/ __)| _ )
  |_| \___ /___) |_| \___ |_|_\  v2.3.0

PHP 7.4.3 (cli) | php | 8 threads

F

-- FAILED: Extension.phpt
   Exited with error code 255 (expected 0)
   E_DEPRECATED: Function ReflectionType::__toString() is deprecated
   
   in src/Utils/Reflection.php(54) 
   in src/DI/Helpers.php(111) Nette\Utils\Reflection::getParameterType()
   in src/DI/ContainerBuilder.php(627) Nette\DI\Helpers::autowireArguments()
   in src/DI/ContainerBuilder.php(572) Nette\DI\ContainerBuilder->completeStatement()
   in src/DI/PhpGenerator.php(48) Nette\DI\ContainerBuilder->complete()
   in src/DI/Compiler.php(257) Nette\DI\PhpGenerator->generate()
   in src/DI/Compiler.php(177) Nette\DI\Compiler->generateCode()
   in src/DI/ContainerLoader.php(118) Nette\DI\Compiler->compile()
   in src/DI/ContainerLoader.php(82) Nette\DI\ContainerLoader->generate()
   in src/DI/ContainerLoader.php(47) Nette\DI\ContainerLoader->loadFile()
   in cases/DI/Extension.phpt(31) Nette\DI\ContainerLoader->load()
   in nunjuck/src/functions.php(18) {closure}()
   in cases/DI/Extension.phpt(50) test()
```

I think it's something that we probably don't need to handle since it's "just" the deprecation in PHP 7.4 and the only way how to solve it is to force `nette/utils: ^3.0.1` which would force Nette 3 everywhere.

The deprecation was fixed here: https://github.com/nette/utils/commit/fb3d29d1dbaa05660e68fa98bec1e43181202b91.

If you see a way how to circumvent it, let me know, otherwise I'll keep it as it is.

2020-10-22 07:51 UTC, rootpd approved these changes

2020-10-22 08:53 UTC, martenb commented
I think, that whole nette 2.4 is not supossed to run on PHP 7.4

2020-10-22 09:07 UTC, merged

2020-10-22 09:16 UTC, rootpd commented
Merged and tagged as `1.2.0`.

2020-10-22 09:17 UTC, martenb commented
Perfect, thx